#! /usr/bin/env bash

# Generate a .hs file with all the components of the .stories.js files.

echo '-- Generated by scripts/create-stories-hs.sh.'
echo 'module Hypered.Stories where'
echo
echo
echo 'stories :: [(String, String)]'
echo 'stories ='

# This component is actually the welcome page.
echo '  [ ("Hypered", "DesignSystem")'

# See the list-stories.sh script for explanations.
grep '^export const' -Ir components/ --include '*.stories.js' \
  | sort \
  | sed -s 's@components/[^/]\+/\([^.]\+\).stories.js:export const \([^ ]\+\) .*@  , ("\1", "\2")@'

echo '  ]'
